name: Danger Systems
description: Run danger as part of your pipeline
inputs:
  repo-token:
    description: Token to use to authorize danger to operate on your PR. Typically the GITHUB_TOKEN secret.
    required: true
  language:
    description: Language to run danger against (ruby, js)
    required: true
    default: js
  language-version:
    description: Language version
    required: false
  dangerfile-path:
    description: Override default dangerfile path
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/bin/command ${{ inputs.repo-token }} ${{ inputs.language }} ${{ inputs.language-version }} ${{ inputs.dangerfile-path }}
      shell: bash
