ARG NODE_IMAGE_VERSION
ARG BASE_IMAGE=node:${NODE_IMAGE_VERSION}-alpine
FROM ${BASE_IMAGE}

ENV LANG=C.UTF-8

RUN echo "Building base image: $BASE_IMAGE"

RUN mkdir /home/app
WORKDIR /home/app

# Set known cache directory for yarn
RUN yarn config set cache-folder /home/yarn-cache

ENV GH_NPM_REGISTRY_TOKEN ""

# ENV vars that danger cares about
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables
ENV GITHUB_TOKEN ""
ENV GITHUB_WORKFLOW ""
