name: Danger System (Ruby)
on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Danger
        uses: cultureamp/danger-systems-github-action@custom-dangerfile-path
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          language: ruby
          language-version: 2.7.1
          dangerfile-path: ./Dangerfile.custom
